name: Check PR Title for Change Level

permissions:
  pull-requests: write
  contents: read

on:
  workflow_call:

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.3
        id: check
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
      
      - name: Add comment to fix PR title
        uses: marocchino/sticky-pull-request-comment@v3
        if: ${{ steps.check.outputs.success == 'false' }}
        with:
          header: 'PR Title Check'
          recreate: true
          message: |
              ### 🚨 PR Title Needs Formatting
              The title of this PR needs to be formatted correctly to include a change level. 
              Please update the title to match the format `(<change-level>) description`. Examples:
              * `(MAJOR) Introduce breaking change`
              * `(MINOR) Add new feature`
              * `(PATCH) Fix bug`

      - name: Add comment that PR title is fixed
        if: ${{ steps.check.outputs.success == 'true' }}
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          header: 'PR Title Check'
          recreate: true
          message: |
              ### ✅ PR Title Formatted Correctly
              The title of this PR has been updated to match the correct format. Thank you!
              
      - name: Fail if PR title is not correct
        if: ${{ steps.check.outputs.success == 'false' }}
        run: exit 1